
EVAL_RUNTIME_SERVICE_URL = "https://qa.sarvam.ai/api/eval_test_runner/"





USERNAME = "sarvam"
ACCESS_CODE = "kQfa~!UwbG*}K,cMu7(Ne?"
automation_xapi_key = 'GHAqcauhGWtHtlbTe1k6GvE1kmSaRwJF'
manual_xapi_key = 'R6Q95mYC0uN6oTVdcYCVLxP3tEijsZ5R'
manual_new_xapi_key = 'yG8F3eJLOOezlYzDQZ4Sj883MnZ2c70e'
conversation_generation_xapi_key = 'CSOYjQe3ApqHTyO4Sy1YcvPBBq1LQWxf'
talk_with_data_xapi_key = '4JcLXXLsZkm5Y9V4WnKUJFvLJmzFCDtZ'